openapi: 3.0.0
info:
  title: 'CodeIgniter 4 API'
  description: 'CodeIgniter 4 sample API swagger documentation'
  version: '1.0'
servers:
  -
    url: 'http://localhost/'
    description: 'Local Server'
components:
  securitySchemes:
    bearerAuth:
      type: http
      in: header
      bearerFormat: JWT
      scheme: bearer
